export {
	useReadFontaine,
	useReadLocker,
	useReadLockerFactory,
	useReadProgramManager,
	useReadStakingRewardController,
	useReadSupToken,
	useSimulateFontaine,
	useSimulateLocker,
	useSimulateLockerFactory,
	useSimulateProgramManager,
	useSimulateStakingRewardController,
	useSimulateSupToken,
	useWatchFontaineEvent,
	useWatchLockerEvent,
	useWatchLockerFactoryEvent,
	useWatchProgramManagerEvent,
	useWatchStakingRewardControllerEvent,
	useWatchSupTokenEvent,
	useWriteFontaine,
	useWriteLocker,
	useWriteLockerFactory,
	useWriteProgramManager,
	useWriteStakingRewardController,
	useWriteSupToken,
} from "./generated.js"
